cors:
  allowed:
    origins: http://localhost:3000

spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3308/catalog
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  kafka:
    enabled: true
    bootstrap-servers: ${kafka.server.url:localhost:9092}
    value-seriliazer: org.apache.kafka.common.serialization.StringSerializer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    producer:
      client-id: kafka-message-producer
      acks: all
    topic:
      book-rating: ${kafka.topic.book-rating:book-rating}

server:
  port: 8081