cors:
  allowed:
    origins: http://localhost:3000

spring:
  datasource:
    url: jdbc:mysql://${mysql.server.host:0.0.0.0}:3308/catalog
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081