cors:
  allowed:
    origins: http://library.productdock.rs

spring:
  cloud:
    gcp:
      sql:
        database-name: catalog
        instance-connection-name: prod-pd-library:europe-west3:prod-pd-library-mysql

  logging.level.c.g.cloud.sql.core.CoreSocketFactory: WARN