spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  jpa:
    hibernate:
      ddl-auto: validate

server:
  error:
    include-message: always
