cors:
  allowed:
    origins: http://library.productdock.rs

spring:
  cloud:
    gcp:
      sql:
        database-name: catalog
        instance-connection-name: prod-pd-library:europe-west3:prod-pd-library-mysql
  flyway:
    user: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    schemas: catalog
    url: jdbc:mysql://google/catalog?cloudSqlInstance=prod-pd-library:europe-west3:prod-pd-library-mysql&socketFactory=com.google.cloud.sql.mysql.SocketFactory
    locations: classpath:db/migration
    baselineOnMigrate: true

logging:
  level:
    com.google.cloud.sql.core.CoreSocketFactory: WARN

jwt:
  public.key: ${catalog.jwt.public.key}