version: '3.1'

services:

  pd-library-catalog-db:
    image: mysql:8-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catalog
    volumes:
      - ./import-catalog.sql:/docker-entrypoint-initdb.d/import-catalog.sql
    ports:
      - "3308:3306"
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_general_ci']

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "book-rating:1:1"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
