name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - feat/automate-deploy

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: prod-pd-library-app
  GCE_INSTANCE_ZONE: europe-west3-c

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/817921738258/locations/global/workloadIdentityPools/rbc-github-pool/providers/rbc-github-action-provider'
          service_account: 'prod-pd-library-vm@prod-pd-library.iam.gserviceaccount.com'

      # Setup gcloud CLI
      - name: Set up Cloud SDK and SSH to VM
        uses: google-github-actions/setup-gcloud@v0

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud compute ssh $GCE_INSTANCE --command="sudo docker pull gcr.io/prod-pd-library/prod-pd-library-app-image:rbc-library"

