name: Build Production And Publish to Docker registry

on:
  push:
    branches:
      - feat/automate-deploy

env:
  DOCKER_IMAGE_NAME: gcr.io/${{ secrets.GCE_PROJECT }}/${{ github.event.repository.name }}

jobs:
  setup-build-publish-deploy:
    name: Build Production Job
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/817921738258/locations/global/workloadIdentityPools/rbc-github-pool/providers/rbc-github-action-provider'
          service_account: 'prod-pd-library-vm@prod-pd-library.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - run: |-
          gcloud auth configure-docker

      - name: Build
        run: |-
          docker build --build-arg PASSWORD=${{ secrets.DATABASE_PASSWORD }} --build-arg ACTIVE_PROFILE=prod --tag "$DOCKER_IMAGE_NAME:latest" .

      - name: Publish
        run: |-
          docker push "$DOCKER_IMAGE_NAME:latest"