name: Build and Deploy Production

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

env:
  DATABASE_PASSWORD: 'PASSWORD=${{ secrets.DATABASE_PASSWORD }}'

jobs:
  build-prod:
    uses: ProductDock/rbc-github-workflows/.github/workflows/build-prod.yml@main
    with:
      update-script: /home/pd-library/update-catalog-image.sh
      docker-build-args: --build-arg $DATABASE_PASSWORD
    secrets: inherit