name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - feat/automate-deploy

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: prod-pd-library-services
  GCE_INSTANCE_ZONE: europe-west3-c
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - run: |-
          echo $REPO_NAME
          gcloud auth configure-docker
