name: Build and Deploy to Google Compute Engine

on:
  workflow_dispatch:

env:
  GCE_INSTANCE: prod-pd-library-services
  GCE_INSTANCE_ZONE: europe-west3-c
  DOCKER_IMAGE_NAME: gcr.io/${{ secrets.GCE_PROJECT }}/${{ github.event.repository.name }}

jobs:
  setup-build-publish-deploy:
    name: Deploy Production Job
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/817921738258/locations/global/workloadIdentityPools/rbc-github-pool/providers/rbc-github-action-provider'
          service_account: 'prod-pd-library-vm@prod-pd-library.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - run: |-
          gcloud auth configure-docker

      - name: SSH to VM
        run: |-
          gcloud compute ssh --project=prod-pd-library --zone=$GCE_INSTANCE_ZONE --ssh-key-expire-after=5m --command="bash /home/pd-library/update-catalog-image.sh" $GCE_INSTANCE
